{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/slodha01/BA870-Project/blob/main/Final_BA870_Streamlit_App.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import streamlit as st\n",
        "import pandas as pd\n",
        "import matplotlib.pyplot as plt\n",
        "import seaborn as sns\n",
        "\n",
        "st.set_page_config(page_title=\"Financial Risk Analyzer\", layout=\"centered\")\n",
        "\n",
        "# Sidebar navigation\n",
        "tabs = [\n",
        "    \"Project Overview\",\n",
        "    \"Dataset Description\",\n",
        "    \"Data Dictionary\",\n",
        "    \"Upload File\",\n",
        "    \"Models\",\n",
        "    \"Implications & Next Step\"\n",
        "]\n",
        "selected_tab = st.sidebar.selectbox(\"Navigate Project Sections\", tabs)\n",
        "\n",
        "# 1. Project Overview\n",
        "if selected_tab == \"Project Overview\":\n",
        "    st.write(\"BA870 Project By: Fan Hong (Sally) Kong, Shreya Lodha, Victoria Carlsten\")\n",
        "    st.title(\"Project Overview\")\n",
        "    st.markdown(\"<h2 style='color: navy;'>Business Problem</h2>\", unsafe_allow_html=True)\n",
        "    st.write(\"\"\"\n",
        "\n",
        "    The project aims to detect financial fraud by identifying anomalies in financial statements using the\n",
        "    **Beneish M-Score** and **Altman’s Z Score**. By applying these fraud detection techniques, we seek to\n",
        "    flag companies that may be manipulating earnings, reducing financial transparency, and posing risks to\n",
        "    investors and creditors.\n",
        "\n",
        "    The objective is to enhance fraud detection methodologies for credit risk assessment and financial\n",
        "    stability evaluation. We will then use the M-score from the Beneish model to try and predict future\n",
        "    bankruptcy of the companies that engage in manipulation.\n",
        "    \"\"\")\n",
        "    st.markdown(\"<h2 style='color: navy;'>Data Set</h2>\", unsafe_allow_html=True)\n",
        "    st.write(\"\"\"\n",
        "    Our dataset was extracted from WRDS using **Compustat** to compile financial and accounting ratio data\n",
        "    from **2010–2024** for publicly traded companies in the **technology industry**.\n",
        "\n",
        "    For more information, visit the **‘Dataset Description’** tab.\n",
        "    \"\"\")\n",
        "\n",
        "# 2. Dataset Description\n",
        "elif selected_tab == \"Dataset Description\":\n",
        "    st.title(\"Dataset Description\")\n",
        "\n",
        "    st.markdown(\"\"\"\n",
        "    **Final Dataset**: Merged_dataset.csv\n",
        "    *(Includes: Fraud.csv, Additional.csv, Financialdata.csv)*\n",
        "\n",
        "    All initial datasets were queried and pulled from the **Wharton Research Data Services (WRDS)** via **Compustat**.\n",
        "    Our team extracted data from the **Fundamentals - Annual** section, filtering for companies in the **technology industry** using the following **SIC codes**:\n",
        "\n",
        "    3570, 3571, 3572, 3575, 3577, 3578, 3579, 3661, 3663, 3669, 3672, 3674, 3675, 3676, 3677, 3678, 3679, 7370, 7371, 7372, 7373, 7374, 7375, 7376, 7379\n",
        "\n",
        "    The **ticker symbols** extracted from this dataset were then used to pull consistent company data in both **Fraud.csv** and **Additional.csv**.\n",
        "    The dataset spans from **2010 to 2024** and contains **annual financial reporting** required for calculating the **Beneish M-Score** and **Altman Z-Score**.\n",
        "\n",
        "    ---\n",
        "\n",
        "    **File Descriptions**\n",
        "\n",
        "    - **Financialdata.csv**\n",
        "      Pulled from **Fundamentals - Annual** in Compustat. This is the **main dataset**, containing common financial statement items necessary for computing the **M-Score** and **Z-Score**.\n",
        "      It also includes identifying fields such as **Ticker symbol**, **Fiscal Year**, **Global Company Key**, and **GIC sector**.\n",
        "\n",
        "    - **Fraud.csv**\n",
        "      Sourced from **Audit Analytics – Financial Restatements** (WRDS), using tickers from Financialdata.csv.\n",
        "      It was used to create **binary fraud labels** for machine learning:\n",
        "      **1 = Fraudulent**, **0 = Non-Fraudulent**.\n",
        "\n",
        "    - **Additional.csv**\n",
        "      Also pulled from **Fundamentals - Annual** in Compustat.\n",
        "      It provided supplemental variables for calculating the **Asset Quality Index** for the **Beneish M-Score**.\n",
        "\n",
        "    ---\n",
        "\n",
        "    For details on specific variable definitions, please refer to the **Data Dictionary** tab.\n",
        "\n",
        "    Below is the data info for the **variables we used** from the final `merged_dataset.csv`.\n",
        "    \"\"\")\n",
        "\n",
        "    # Show image\n",
        "    st.image(\n",
        "       \"https://raw.githubusercontent.com/slodha01/BA870-Project/6d5b485387552e07df58265b64d126ec35eec19e/Photos/Dataset_info.png\",\n",
        "       caption=\"Merged Dataset: Variable Overview\",\n",
        "        use_container_width=True)\n",
        "\n",
        "\n",
        "\n",
        "# 3. Data Dictionary\n",
        "elif selected_tab == \"Data Dictionary\":\n",
        "    st.title(\"Dataset Dictionary\")\n",
        "\n",
        "    # Fraud.csv Data Dictionary\n",
        "    st.subheader(\"Fraud.csv Variables\")\n",
        "    fraud_dict = {\n",
        "        \"Column Name\": [\n",
        "            \"RESTATEMENT_NOTIFICATION_KEY\",\n",
        "            \"RESTATEMENT_TYPE_FKEY\",\n",
        "            \"RESTATEMENT_TYPE\",\n",
        "            \"FILE_DATE\",\n",
        "            \"COMPANY_FKEY\",\n",
        "            \"BEST_EDGAR_TICKER\",\n",
        "            \"is_fraud\"\n",
        "        ],\n",
        "        \"Description\": [\n",
        "            \"Restatement Notification Key\",\n",
        "            \"Restatement Type Key\",\n",
        "            \"Restatement Type\",\n",
        "            \"File Date\",\n",
        "            \"Company Key\",\n",
        "            \"Best Edgar Ticker\",\n",
        "            \"If company committed fraud (1 = committed, 0 = not commit)\"\n",
        "        ]\n",
        "    }\n",
        "    st.dataframe(pd.DataFrame(fraud_dict))\n",
        "\n",
        "    # Financialdata.csv & additional.csv Data Dictionary\n",
        "    st.subheader(\"Financialdata.csv & additional.csv Variables\")\n",
        "    financial_dict = {\n",
        "        \"Column Name\": [\n",
        "            \"Ivao\", \"ivst\", \"gvkey\", \"datadate\", \"fyear\", \"indfmt\", \"consol\", \"popsrc\", \"datafmt\", \"tic\",\n",
        "            \"conm\", \"curcd\", \"fyr\", \"act\", \"at\", \"cogs\", \"dltt\", \"dp\", \"intan\", \"ist\", \"lt\", \"ni\", \"oancf\",\n",
        "            \"ppegt\", \"rect\", \"revt\", \"urect\", \"xopr\", \"xsaga\", \"costat\", \"gsector\", \"gsubind\", \"idbflag\", \"sic\"\n",
        "        ],\n",
        "        \"Description\": [\n",
        "            \"Investment and Advances - Other\", \"Short-Term Investments - Total\", \"Global Company Key\",\n",
        "            \"Data Date\", \"Data Year - Fiscal\", \"Industry Format\", \"Consolidation Code\", \"Population Source\",\n",
        "            \"Data Format\", \"Ticker\", \"Company Name\", \"ISO Currency Code\", \"Fiscal Year-end Month\",\n",
        "            \"Current Assets - Total\", \"Current Assets - Total\", \"Cost of Goods Sold\", \"Long-Term Debt - Total\",\n",
        "            \"Depreciation and Amortization\", \"Intangible Assets - Total\", \"Investment Securities - Total\", \"Liabilities - Total\", \"Net Income\", \"Operating Activities - Net Cash Flow\",\n",
        "            \"Property, Plant, and Equipment - Total\", \"Receivables - Total\", \"Revenue - Total\", \"Receivables (Net)\",\n",
        "            \"Operating Expenses - Total\", \"Selling, General, & Administrative Expense\", \"Active/ Inactive Status Market\",\n",
        "            \"GIC Sector\", \"GIC Sub-Industries\", \"International, Domestic, Both Indicator\",\n",
        "            \"Standard Industry Classification Code\"\n",
        "        ]\n",
        "    }\n",
        "    st.dataframe(pd.DataFrame(financial_dict))\n",
        "\n",
        "# 4. Beneish Model\n",
        "elif selected_tab == \"Models\":\n",
        "    st.title(\"Beneish M-Score & Altman Z-Score Model\")\n",
        "\n",
        "    st.markdown(\"### Beneish M-Score Model\")\n",
        "    st.write(\"\"\"\n",
        "    We built a **binary classification model** to predict the likelihood of financial fraud using the **Beneish M-Score** framework.\n",
        "\n",
        "    - The dataset was **chronologically split** by fiscal year:\n",
        "      **Training** = data before 2018\n",
        "      **Testing** = data from 2018 onward\n",
        "\n",
        "    - Two models were trained:\n",
        "      - **Random Forest Classifier**\n",
        "      - **XGBoost**\n",
        "\n",
        "    - The target variable was **`is_fraud`**, and both models used **eight financial ratios** derived from company financial statements.\n",
        "\n",
        "    - The **Random Forest** model achieved an **accuracy of 93.4%**.\n",
        "      Due to dataset imbalance, we also evaluated model performance using a **confusion matrix** for more reliable insights.\n",
        "    \"\"\")\n",
        "\n",
        "    col1, col2 = st.columns(2)\n",
        "\n",
        "    with col1:\n",
        "        st.image(\n",
        "            \"https://raw.githubusercontent.com/slodha01/BA870-Project/eb401490034ef4d92560ed7f27dada0b4ddf18ba/Photos/Radar_Chart.png\",\n",
        "            caption=\"Radar Chart: Financial Ratios Used in Beneish Model\",\n",
        "            use_container_width=True\n",
        "        )\n",
        "\n",
        "    with col2:\n",
        "        st.image(\n",
        "            \"https://raw.githubusercontent.com/slodha01/BA870-Project/ae368f60adf54b40e2990626a083fa6e9c216dd7/Photos/Bar_Chart.png\",\n",
        "            caption=\"Bar Chart: Feature Importance in Random Forest Model\",\n",
        "            use_container_width=True\n",
        "        )\n",
        "\n",
        "    # Dedent this part to be OUTSIDE the 'with' block\n",
        "    st.markdown(\"### Altman’s Z-Score\")\n",
        "    st.write(\"\"\"\n",
        "    We used the **Z-Score** to estimate the **likelihood of bankruptcy**, combining five key financial ratios.\n",
        "\n",
        "    - Initially, we implemented the **classic Z-Score formula** for publicly traded manufacturing firms.\n",
        "      However, we found that these thresholds were not well-suited to the **technology industry**, due to its unique capital structures.\n",
        "\n",
        "    - As a result, we **adjusted the classification bounds** to better reflect risk in the tech sector.\n",
        "\n",
        "    #### Z-Score Classifications:\n",
        "    - **Safe**: Z > 2.9\n",
        "    - **Grey Zone**: 1.23 < Z < 2.9\n",
        "    - **Distress**: Z < 1.23\n",
        "\n",
        "    > Note: The Z-Score was **not used as a predictor** in the fraud model, but rather as a **complementary tool** to contextualize risk.\n",
        "    \"\"\")\n",
        "\n",
        "# 5. Upload File\n",
        "elif selected_tab == \"Upload File\":\n",
        "    st.title(\"Upload Your Processed Dataset (CSV)\")\n",
        "    uploaded_file = st.file_uploader(\"Upload your file\", type=\"csv\")\n",
        "\n",
        "    if uploaded_file:\n",
        "        df = pd.read_csv(uploaded_file)\n",
        "\n",
        "        required_cols = {'is_fraud', 'z_score', 'bankruptcy_risk'}\n",
        "        if not required_cols.issubset(df.columns):\n",
        "            st.error(f\"Your dataset must contain the following columns: {', '.join(required_cols)}\")\n",
        "        else:\n",
        "            st.success(\"File successfully loaded!\")\n",
        "\n",
        "            with st.expander(\"View raw data\"):\n",
        "                st.dataframe(df.head())\n",
        "\n",
        "            st.subheader(\"Fraud vs. Bankruptcy Risk Counts\")\n",
        "            summary = df.groupby(['is_fraud', 'bankruptcy_risk']).size().reset_index(name='count')\n",
        "            st.dataframe(summary)\n",
        "\n",
        "            st.subheader(\"Risk Distribution Chart\")\n",
        "            fig, ax = plt.subplots(figsize=(8, 5))\n",
        "            sns.countplot(data=df, x='bankruptcy_risk', hue='is_fraud', palette='Set2', ax=ax)\n",
        "            ax.set_title('Fraud Risk vs. Bankruptcy Risk')\n",
        "            ax.set_xlabel(\"Bankruptcy Risk Category\")\n",
        "            ax.set_ylabel(\"Number of Companies\")\n",
        "            ax.legend(title=\"Fraudulent (Beneish M-Score)\", labels=[\"No\", \"Yes\"])\n",
        "            st.pyplot(fig)\n",
        "\n",
        "            st.subheader(\"Altman Z′-Score Summary\")\n",
        "            stats = df.groupby('is_fraud')['z_score'].agg(['mean', 'median', 'std', 'count']).rename(\n",
        "                index={0: 'Non-Fraud', 1: 'Fraud'}\n",
        "            )\n",
        "            st.dataframe(stats)\n",
        "    else:\n",
        "        st.info(\"Upload a CSV to begin.\")\n",
        "\n",
        "# 6. Implications & Next Step\n",
        "elif selected_tab == \"Implications & Next Step\":\n",
        "    st.title(\"Implications of Fraud Detection\")\n",
        "\n",
        "    st.markdown(\"Next Steps\")\n",
        "\n",
        "    st.markdown(\"\"\"\n",
        "    **Further Analysis with Industry-Specific Benchmarks**\n",
        "    - While we focused our analysis on companies within the technology sector, we aim to refine the threshold cutoffs using industry-specific benchmarks. By customizing these bounds, we hope to better capture financial distress risk in sector-specific contexts.\n",
        "\n",
        "    **Incorporating More Variables**\n",
        "    - Additionally, we plan to incorporate more variables into the model, such as changes in auditors, board composition, and broader industry sentiment. These indicators can serve as early warning signals that are often overlooked by financial ratios alone.\n",
        "\n",
        "    **Textual Analysis Modeling**\n",
        "    - To improve the predictive power of our model, we would also like to incorporate text-based features derived from company disclosures. Using Natural Language Processing (NLP) techniques, we can analyze earnings call transcripts and other qualitative data available. These unstructured data sources can contain qualitative signals, like vague language or increased mention of risk, that precede financial misconduct or distress.\n",
        "    \"\"\")\n"
      ],
      "metadata": {
        "id": "x82i5FHsJA42"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}