# -*- coding: utf-8 -*-
"""Streamlit App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dnMBO4kT6kIgv7-us6p_5jGqQeWh6L9D
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

st.set_page_config(page_title="Financial Risk Analyzer", layout="centered")
st.title("📉 Financial Risk Analyzer")
st.markdown("Analyze earnings manipulation (Beneish M-Score) and bankruptcy risk (Altman Z′-Score).")

# File upload
uploaded_file = st.file_uploader("📂 Upload your processed dataset (CSV)", type="csv")

if uploaded_file:
    df = pd.read_csv(uploaded_file)

    # Validate required columns
    required_cols = {'is_fraud', 'z_score', 'bankruptcy_risk'}
    if not required_cols.issubset(df.columns):
        st.error(f"❌ Your dataset must contain the following columns: {', '.join(required_cols)}")
    else:
        st.success("✅ File successfully loaded!")

        # Show data preview
        with st.expander("🔍 View raw data"):
            st.dataframe(df.head())

        # Summary table
        st.subheader("📊 Fraud vs. Bankruptcy Risk Counts")
        summary = df.groupby(['is_fraud', 'bankruptcy_risk']).size().reset_index(name='count')
        st.dataframe(summary)

        # Visualization
        st.subheader("📈 Risk Distribution Chart")
        fig, ax = plt.subplots(figsize=(8, 5))
        sns.countplot(data=df, x='bankruptcy_risk', hue='is_fraud', palette='Set2', ax=ax)
        ax.set_title('Fraud Risk vs. Bankruptcy Risk')
        ax.set_xlabel("Bankruptcy Risk Category")
        ax.set_ylabel("Number of Companies")
        ax.legend(title="Fraudulent (Beneish M-Score)", labels=["No", "Yes"])
        st.pyplot(fig)

        # Z-score statistics
        st.subheader("📐 Altman Z′-Score Summary")
        stats = df.groupby('is_fraud')['z_score'].agg(['mean', 'median', 'std', 'count']).rename(
            index={0: 'Non-Fraud', 1: 'Fraud'}
        )
        st.dataframe(stats)

else:
    st.info("👆 Upload a CSV to begin.")